### PR TITLE
feat: talismanWallet support

### PR DESCRIPTION
**Pull request by 0xKheops**
Hi Rainbow team,

This PR adds Talisman to the list of supported wallets, to help our users connecting to rainbowkit dapps.

Please let me know if anything needs to be added or changed to satisfy your requirements.

Cheers, 
Kheops

### CODE REVIEW

**Comment by 0xKheops** [comment]
Sorry about this, didn't do things in the right order.

The missing `isTalisman` flag has been released in `wagmi@1.0.5`.
https://github.com/wagmi-dev/references/pull/289

I'll wait until next rainbowkit deps bump, and will then update this PR.

**Comment by 0xKheops** [comment]
Branch synchronized, it should be ok now.
If testing manually, please ensure you use Talisman 1.16.3 (current version).

**Comment by 0xKheops** [comment]
Hi @DanielSinclair,
Any idea why the rainbowkit-example didn't deploy ? i don't have access on vercel side

**Comment by 0xKheops** [comment]
@DanielSinclair is there anything else I can do to help getting this merged ?

**Comment by DanielSinclair** [comment]
@0xKheops Please enable changes from maintainers on this PR

**Comment by 0xKheops** [comment]
@DanielSinclair sorry i can't, this is a PR originating coming from Talisman org
I just synchronized, is it ok or do you need me to recreate it with my personal account ?

**Comment by DanielSinclair** [comment]
@0xKheops Yes, will unfortunately need access for some small changes before merging. Aiming to merge a batch of connectors later today, so feel free to open another PR and will prioritize.

**Pull request closed without merging**
