### PR TITLE
feat: add desktop download URL and instructions

### PR DESCRIPTION
**Pull request by hlopes-ledger**
- add a downloadUrls.desktop property
- add a wallet.desktop.instructions property
- set these on the Ledger connector to present desktop and mobile app download buttons for Ledger Live

demo here: https://645e04523bc76170fcab5872--ledger-rainbowkit-demo.netlify.app

testing:

- choose the Ledger Live wallet
- refuse to open Ledger Live when prompted
- press "GET"
- there should be app install buttons for desktop and mobile
- after pressing "Get the desktop app" it should show the instructions
- pressing "Connect" should take you back to the QR code screen and prompt you to open Ledger Live Desktop

image
image

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@hlopes-ledger Thanks for working on this flow. Will try to get reviewed and merged this week!

**Review by DanielSinclair — APPROVED** [review]

**Comment by DanielSinclair** [comment]
After testing, am seeing an issue on the Ledger Live Desktop flow where the UI doesn't properly route before the the desktop deep link is fired.
Before:
Screenshot 2023-07-06 at 3 41 24 PM
After:
Screenshot 2023-07-06 at 3 41 16 PM

**Comment by hlopes-ledger** [comment]
> After testing, am seeing an issue on the Ledger Live Desktop flow where the UI doesn't properly route before the the desktop deep link is fired.
> Before:
> Screenshot 2023-07-06 at 3 41 24 PM
> After:
> Screenshot 2023-07-06 at 3 41 16 PM

On the demo URL you shared I see the following error on the console:

Uncaught (in promise) TypeError: Cannot destructure property 'uri' of '(intermediate value).connector' as it is undefined.

but I've tried it on a custom app and running the with-vite demo from the repo and it worked as expected on both.

**Comment by hlopes-ledger** [comment]
I've added a comment when I closed it, "Closing as Ledger will stop promoting the Extension and pause its development for the time being."

The Ledger Extension will not be developed further in the near future, so we'll be using Wallet Connect only for now.

**Comment by DanielSinclair** [comment]
@hlopes-ledger I see. Thanks for the heads up. Will still move forward with this PR and the name change, and would be happy to pick back up on the extension provider support if that moves forward in the future!

**Comment by tjulien-ledger** [comment]
Hi @DanielSinclair is there anything we can do to help move forward with merging this PR please?

**Comment by ComradeAERGO** [comment]
Hi @DanielSinclair 
I'm taking over as @hlopes-ledger no longer works on this project. Please tell us if there's anything we an do to help you merge this PR

**Review by DanielSinclair — APPROVED** [review]

**Comment by DanielSinclair** [comment]
@ComradeAERGO @tjulien-ledger Merging this today after taking care of changes and QA on our end, but is your team actually referring to and hoping for the #1237 PR that Hugo had closed? This PR only adds an additional download button to the Ledger flow to cleanup the Ledger Live onboarding UX on Desktop.

**Review by 0xmkh — APPROVED** [review]
Looks good to me 👍

**Comment by ComradeAERGO** [comment]
> @ComradeAERGO @tjulien-ledger Merging this today after taking care of changes and QA on our end, but is your team actually referring to and hoping for the #1237 PR that Hugo had closed? This PR only adds an additional download button to the Ledger flow to cleanup the Ledger Live onboarding UX on Desktop.

Thanks a lot. We just want to make sure this our flows are optimal across libraries.

**Pull request merged**
