### PR TITLE
docs: add codesandbox (stackblitz) link for vite in readme and docs site

### PR DESCRIPTION
**Pull request by Dhaiwat10**
### Context
This PR adds a link to a [Stackblitz](https://stackblitz) container running a Vite project setup with Rainbowkit. The link has been added to the readme and the docs site where other Codesandbox links have been mentioned.

I literally couldn't find a Vite + TS template that works properly on Codesandbox so had to use Stackblitz 😅

### CODE REVIEW

**Comment by nickbytes** [comment]
@Dhaiwat10 thanks for the contribution here! Love seeing a project w/ Vite + RainbowKit.

Our team is going to discuss how we go about adding/linking more examples for using different build tooling, frameworks, etc etc. 

We worry that by linking out to external examples that we don't own, we may expose our users to risks of interacting with malicious applications. If we add them to our `/examples` folder, we worry that we will be responsible for keeping these up to date. Over time, this will lead to a ton of issues + work to keep examples up to date and we'd rather that time and energy be spent building new features.

Let me discuss more w/ the team and we'll get back to you. In the meantime, you should definitely publish this as a starter kit yourself! I'm sure people would find it helpful.

**Comment by Dhaiwat10** [comment]
@nickbytes that sounds fair, thanks! :)

**Comment by nickbytes** [comment]
@Dhaiwat10 we're going to close this and focus our efforts elsewhere – primarily, developing new features and doubling down on education through our social channels. We appreciate the PR and hope that you will continue to be a great part of the community!

**Comment by Dhaiwat10** [comment]
No worries Nick!

**Pull request closed without merging**
