### PR TITLE
feat: fordefiWallet support

### PR DESCRIPTION
**Pull request by rony-arnac**
Hey Rainbowkit team,

Opening this PR to support [Fordefi](https://www.fordefi.com) browser wallet.
Fordefi is an institutional crypto wallet and works with all dApp websites.

Note that I have a pending PR to [add Fordefi to wagmi](https://github.com/wagmi-dev/references/pull/417).
So I will wait for it to be merged first, before merging this one.

Please let me know if there's anything I can do to support this PR and get it merged.

Thanksss

---
Rony Fragin
Extension Owner
[Fordefi](https://www.fordefi.com)
FordefiLogoAuth0

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@rony-arnac It looks the CI and deployments had failed here.

**Comment by DanielSinclair** [comment]
@rony-arnac Seeing CI/deployment errors. Please correct.

**Comment by rony-arnac** [comment]
@DanielSinclair thanks! pushed fixes

**Comment by DanielSinclair** [comment]
@rony-arnac Seeing some more lint errors

**Comment by rony-arnac** [comment]
@DanielSinclair fixed

**Comment by DanielSinclair** [comment]
@rony-arnac Still seeing some linting errors

**Comment by DanielSinclair** [comment]
@rony-arnac Tests are now passing. How should I QA this connector? Is the wallet widely available? If not, it is often better to create a custom connector for internal use in dApps rather than distribute a connector within RainbowKit.

**Comment by rony-arnac** [comment]
@DanielSinclair we are a B2B company and our customers are using the Fordefi wallet.
Unfortunately it can't be tested without being our customer..

**Comment by DanielSinclair** [comment]
@rony-arnac You can create a [Custom Wallet](https://www.rainbowkit.com/docs/custom-wallets) with our API and distribute that in internal dApps. Other products that target enterprise with companion extensions have used this approach. dApps must include your connector in their dApp for it to be recognized for end-users, so the typical distributed connector approach won't be viable for your product as you will have minimal inclusion. The better approach that you'll want to take is to support EIP-6963 in your extension with [mipd](https://github.com/wagmi-dev/mipd) and this will automatically be recognized by RainbowKit in a future release within the next few weeks/months.

**Pull request closed without merging**
