### PR TITLE
feat: dawnWallet

### PR DESCRIPTION
**Pull request by thomas-waite**
## Add Dawn Wallet
Dawn Wallet is an iOS Ethereum Wallet with a native Safari extension: https://twitter.com/dawn_wallet. On Safari, it injects into the webpage a provider, through which the dapp can trigger a popup, connection requests, transaction signing etc.

This PR adds support for Dawn Wallet into RainbowKit.

### CODE REVIEW

**Comment by thomas-waite** [comment]
@DanielSinclair Would appreciate if you could authorise the Vercel preview so I can test in a production environment. Thanks!

**Comment by DanielSinclair** [comment]
@thomas-waite Done ✅

**Comment by thomas-waite** [comment]
> @thomas-waite Done ✅

Great thanks. I've tested it out and it all looks like it's working well as expected. If you want to try, our open testflight link is: [http://testflight.apple.com/join/UHmOJnNy](https://t.co/aGmfQuQaVi) 

One thing to point out. In our provider we currently have an `isMetaMask` flag and we run a script through the extension to replace the `MetaMask` word with `Dawn`. It's a bootstrapping technique, we plan to remove once we're in all the connectors and you can easily access Dawn. 

If that's good (we'll either submit a future PR to add the `isDawn` check to your MetaMask detection code, or put it behind a feature flag ourselves), think we're ready

**Comment by DanielSinclair** [comment]
@thomas-waite We'd prefer if the overrides were disabled; it creates a worse UX for RainbowKit and defeats the purpose of merging in the wallet connector. You can detect RainbowKit by looking for a `<div data-rk>` wrapper div.
Selector | Get Wallet 
--- | ---
IMG_5960 | IMG_5961

**Comment by thomas-waite** [comment]
> @thomas-waite We'd prefer if the overrides were disabled; it creates a worse UX for RainbowKit and defeats the purpose of merging in the wallet connector. You can detect RainbowKit by looking for a `<div data-rk>` wrapper div.
> 
> Selector	Get Wallet
> IMG_5960	IMG_5961

Makes sense. I've disabled the overrides in the latest version of Dawn - the build is ready, I'll release it when this connector PR is merged so we maintain users being able to connect on dapps that use RainbowKit. 

I've attached a screenshot here of what it looks like on a local build of the wallet
RainbowKit Example

I've also added a `(!isDawn)` check to the RainbowKit MetaMask detection code.

**Comment by DanielSinclair** [comment]
@thomas-waite Great, thanks for making that change. Let me know when it's ready to test on the TestFlight track

**Comment by thomas-waite** [comment]
> @thomas-waite Great, thanks for making that change. Let me know when it's ready to test on the TestFlight track

All good to go, have dm'ed you the link

**Comment by DanielSinclair** [comment]
@thomas-waite Looks good. Will cherry-pick to another branch for release.

**Pull request closed without merging**
