### PR TITLE
chore: update rabbyWallet name, logo

### PR DESCRIPTION
**Pull request by dmy147**

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@dmy147 Are you affiliated with the Rabby project? We typically only adopt changes driven by wallet teams directly. Wallet name changes would also first need to be adopted by Wagmi. RainbowKit partially relies on Wagmi's [getInjectedName](https://github.com/wagmi-dev/references/blob/3fcae4f6a456ec44a4f2920ee58885d695f40d29/packages/connectors/src/utils/getInjectedName.ts#LL3C17-L3C32) function.

**Comment by dmy147** [comment]
@DanielSinclair Thank you for your time and attention to this matter.  I'm affiliated with the Rabby project. Could you please reopen this pull request now that the required update has been completed https://github.com/wagmi-dev/references/pull/299 .

**Comment by DanielSinclair** [comment]
@dmy147 Sure. 1 last request! Can you match the SVG sizing, and minify with svgo. If you mark the PR with "Allow edits from maintainers", can also take care of that.

**Comment by dmy147** [comment]
@DanielSinclair Sure, marked the PR with "Allow edits from maintainers";

**Review by nickbytes — APPROVED** [review]

**Pull request merged**
