### PR TITLE
feat: add Steakwallet to list of available wallets

### PR DESCRIPTION
**Pull request by AlexBHarley**
Awesome stuff with this modal library team, at Steakwallet we've been eagerly awaiting its release for a while now.

### CODE REVIEW

**Comment by nickbytes** [comment]
@AlexBHarley thanks for the contribution! Big fan of Steakwallet.

Would you mind updating the docs to add Steakwallet similar to [this imToken PR](https://github.com/rainbow-me/rainbowkit/pull/325/files)?

**Comment by nickbytes** [comment]
@AlexBHarley would you mind if I take this PR to completion? (You'll still get contribution credit, as I'll just add commits to this PR.) Few things I want to update before we get this merged and I don't want to make you go back and forth for small issues:

1. We're having conversations about docs internally, and feel like we don't need mention every wallet in every location on the docs (i.e. on the "Cool Mode" section). We will still include Steakwallet on the Custom Wallets section. We'll also still include Steakwallet on the rainbowkit.com example.
2. We're not going to add any more wallets to `getDefaultWallets` right now. As you can see, `getDefaultWallets` is a convenience function for adding a a group of wallets with a `groupName`. In the future, we're hoping people will publish their own wallet groups and preferences and not rely on ours. We'd rather not add any more wallets here and then be forced to include all wallets in this function. As we expand our docs, we'd like to show other configurations and highlight how any grouping of wallets could be displayed as "Popular" (or whatever grouping name you'd like).

If we can make these changes, we'll be ready to merge this PR. Sorry for the back and forth on the docs. Like I said, happy to make these changes myself to save you some time, let me know.

**Comment by markdalgleish** [comment]
Hey @AlexBHarley, I tried pushing some updates to your branch but I don't seem to have write access. Are you able to double check the permissions?

I've pushed the updates to https://github.com/rainbow-me/rainbowkit/tree/steakwallet if you want to reference them.

**Comment by AlexBHarley** [comment]
@markdalgleish thanks for that, pushed your changes to this branch

**Review by markdalgleish — APPROVED** [review]
Nice one! 👍

**Comment by markdalgleish** [comment]
Out now in v0.1.2: https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.1.2

**Pull request merged**
