### PR TITLE
feat: support berasigWallet

### PR DESCRIPTION
**Pull request by ethanpx**
Hi Rainbow Kit Team,

We have published our wallet to the public, and we kindly request your assistance in reviewing the PR. Please let us know what steps we need to take to manage this PR effectively so we can merge it.

Thank you for your attention to this matter! We look forward to your feedback.

### CODE REVIEW

**Comment by thiennv-qng** [comment]
Hi Rainbow Kit Team, (cc @DanielSinclair )

I’m following up on the PR we submitted regarding our wallet, as it’s been some time without an update. This is an urgent matter for us, and we kindly request your immediate attention to review and provide feedback on the PR.

Please let us know if there are any outstanding steps or concerns on your end so we can address them promptly and proceed with merging. Your timely response is crucial for us to move forward.

Thank you for prioritizing this, and we hope to hear from you soon.

Best regards

**Comment by DanielSinclair** [comment]
@thiennv-qng Please enable edits from maintainers: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by thiennv-qng** [comment]
> @thiennv-qng Please enable edits from maintainers: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I don't see the 'Allow edits and access to secrets by maintainers' option in my PR. Could it be disabled in the repo settings? If so, how would you like me to incorporate the requested changes?

Screenshot 2024-11-26 at 14 02 15

**Comment by DanielSinclair** [comment]
@thiennv-qng Must be an org configuration issue then. Just need the changes to all locale files except `en_US.json` reverted. We maintain those through a separate system.

**Comment by DanielSinclair** [comment]
Had to make additional tweaks and merged in: #2253

**Pull request closed without merging**
