### PR TITLE
Add Ankr as RPC provider

### PR DESCRIPTION
**Pull request by jcstein**
This is a PR to add Ankr's RPCs for ETH Mainnet and Polygon.

### CODE REVIEW

**Comment by wong2** [comment]
I don't think this is necessary. It's already covered by `JSON RPC` section.

**Comment by markdalgleish** [comment]
Thanks for the PR — I'm going to have to close this though since, as @wong2 pointed out, this usage is already covered by the `apiProvider.jsonRpc` section and doesn't require specific documentation.

**Comment by dabit3** [comment]
Curious why Infura and Alchemy are supported specifically but not others?

**Comment by nickbytes** [comment]
> Curious why Infura and Alchemy are supported specifically but not others?

@dabit3 we're down to support other RPC providers, especially those supported by Ethers (like Ankr and Pokt) – but this PR didn't actually add a first-class `apiProvider`, it used the already created `jsonRpc` from `apiProvider`. 

If you want to add an Ankr provider (like Alchemy's and Infura's) feel free to re-open this PR w/ changes @jcstein – check out the [providers mentioned here](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/chains/apiProviders/index.ts) and reach out if you're having any issues.

**Comment by jcstein** [comment]
> > Curious why Infura and Alchemy are supported specifically but not others?
> 
> @dabit3 we're down to support other RPC providers, especially those supported by Ethers (like Ankr and Pokt) – but this PR didn't actually add a first-class `apiProvider`, it used the already created `jsonRpc` from `apiProvider`.
> 
> If you want to add an Ankr provider (like Alchemy's and Infura's) feel free to re-open this PR w/ changes @jcstein – check out the [providers mentioned here](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/chains/apiProviders/index.ts) and reach out if you're having any issues.

Awesome, @nickbytes and thank you @dabit3. Although we are an official provider for Ethers.js, we are waiting on the PR to be merged to add us into the providers that you linked

**Comment by dabit3** [comment]
Ah ok yes that makes sense to me after looking at the code 😅, thanks for your time and response here

**Comment by codingwithmanny** [comment]
Might be part of wagmi in this PR too https://github.com/tmm/wagmi/pull/451

**Pull request closed without merging**
