### PR TITLE
feat: subWallet support

### PR DESCRIPTION
**Pull request by S2kael**
Here is a PR to add [SubWallet](https://www.subwallet.app/) connector to Rainbowkit.

Let me know if anything is missing

Thank you!

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@S2kael Please revert the package.json changes, rebase, and allow edits from maintainer on the PR

**Comment by DanielSinclair** [comment]
Will just need to amend the changeset, so please enabled edits from maintainers. Thanks!

**Comment by S2kael** [comment]
> Will just need to amend the changeset, so please enabled edits from maintainers. Thanks!


How can i enable this?

**Comment by S2kael** [comment]
@DanielSinclair, the PR is from the organization's repository so this option cannot be enabled.
If you have any problem, please DM me to solve it.
Thank you.

**Comment by DanielSinclair** [comment]
@S2kael Just need to correct the changeset to mirror below. Also need to remove the rounded rect on the icon, resize the SVG to 28 x 28, and minify the SVG with svgo. You can also permission me on the repo and that will work as well.

````
---
'@rainbow-me/rainbowkit': patch
---

OneKey Wallet Support

**Example usage**

```ts
import {
  getDefaultWallets,
  connectorsForWallets,
} from '@rainbow-me/rainbowkit';
import { oneKeyWallet } from '@rainbow-me/rainbowkit/wallets';
const { wallets } = getDefaultWallets({ appName, projectId, chains });
const connectors = connectorsForWallets([
  ...wallets,
  {
    groupName: 'Other',
    wallets: [oneKeyWallet({ chains })],
  },
]);
```
````

**Comment by S2kael** [comment]
@DanielSinclair , Does this pull request matter? Please message me to fix this error if any.

**Comment by S2kael** [comment]
Hey @DanielSinclair, please let me know if we are good to go now, or should you suggest us to do anything else? Our partners have been waiting for the PR to be merged for a while. Thank you very much and looking forward!

**Comment by DanielSinclair** [comment]
Closing in favor of #1564 with maintainer changes

**Pull request closed without merging**
