### PR TITLE
feat: tokenaryWallet support

### PR DESCRIPTION
**Pull request by grachyov**

### CODE REVIEW

**Comment by grachyov** [comment]
@DanielSinclair it should be ok now
Screenshot 2023-11-05 at 14 17 48

**Comment by DanielSinclair** [comment]
@grachyov Seeing some lint errors. Run `pnpm lint` to reproduce

**Comment by grachyov** [comment]
@DanielSinclair thanks, fixed it

**Review by DanielSinclair — APPROVED** [review]

**Comment by grachyov** [comment]
thank you @DanielSinclair !

**Pull request merged**
