### PR TITLE
feat: update logo

### PR DESCRIPTION
**Pull request by web3luhao**
we are changing to new logo

### CODE REVIEW

**Comment by magiziz** [comment]
@web3luhao Thanks for raising the PR. Do you know if FoxWallet is supporting EIP-6963 ? Just wondering since we might also add some changes to this PR to support EIP-6963.

**Comment by web3luhao** [comment]
> @web3luhao Thanks for raising the PR. Do you know if FoxWallet is supporting EIP-6963 ? Just wondering since we might also add some changes to this PR to support EIP-6963.

yes we do support EIP-6963.

**Comment by magiziz** [comment]
@web3luhao Can you link me to the correct browser extension link for chrome ? Seems like on the website it shows "The item is not available" https://foxwallet.com

**Comment by web3luhao** [comment]
> @web3luhao Can you link me to the correct browser extension link for chrome ? Seems like on the website it shows "The item is not available" https://foxwallet.com

Don't link to the browser extension for now, our browser extension is new, and haven't support evm yet. not sure why it's not available, I'll check it.

**Comment by magiziz** [comment]
@web3luhao Sounds good 👌

**Review by DanielSinclair — APPROVED** [review]

**Pull request merged**
