### PR TITLE
feat: berasigWallet support

### PR DESCRIPTION
**Pull request by ethanpx**
Hey Rainbowkit team,

I am opening this PR as we have a closed beta right now, and several dApps that want to participate use Rainbowkit for their modal.

Please let me know if there's anything I can do to support this PR and get it merged.

### CODE REVIEW

**Comment by DanielSinclair** [comment]
We try to keep our wallet connectors to publicly available wallets. Let me know when it launches and we'll reopen this. In the meantime, a Custom Wallet Connector can be adopted by dApps.

**Comment by thiennv-qng** [comment]
> We try to keep our wallet connectors to publicly available wallets. Let me know when it launches and we'll reopen this. In the meantime, a Custom Wallet Connector can be adopted by dApps.

Hi @DanielSinclair 
I'm sorry, it seems like I’ve caused some misunderstanding here. Our wallet has already been launched, and the closed beta I mentioned refers to our partner trying to integrate our wallet through Rainbow. Here are the links to download our wallet on the [Chrome Extension](https://chromewebstore.google.com/detail/berasig/ckedkkegjbflcfblcjklibnedmfjppbj) Store and the [Apple Store](https://apps.apple.com/us/app/berasig-wallet-on-berachain/id6502052535).

Due to policy issues, our wallet is still in the testing and review process on Google Play. Will this affect the PR?

**Comment by thiennv-qng** [comment]
Our wallet application has successfully passed the review process and is now live on Google Play. You can access it here: [Google Play Store](https://play.google.com/store/apps/details?id=io.berasig.ios). Please let me know if there are any additional steps or updates required for my pull request to be merged.

**Comment by thiennv-qng** [comment]
@DanielSinclair please help

**Pull request closed without merging**
