### PR TITLE
Kresus Wallet 

### PR DESCRIPTION
**Pull request by Chanchal-NetObjex**
Pull Request for the addition of Kresus Wallet to the Rainbow Wallet Repository

### CODE REVIEW

**Comment by KosmosKey** [comment]
@Chanchal-NetObjex Any reason why Kresus wallet is not working with WalletConnect ?

image

**Comment by Chanchal-NetObjex** [comment]
> @Chanchal-NetObjex Any reason why Kresus wallet is not working with WalletConnect ?
> 
> image

Hey @KosmosKey. Could you mention which chain your trying to connect to?

**Comment by KosmosKey** [comment]
@Chanchal-NetObjex Ethereum

**Comment by KosmosKey** [comment]
@Chanchal-NetObjex Will close this PR to update to the newest RainbowKit v2 connector. We'll add this as soon as possible. Thank you for adding those changes 🙏

PR: https://github.com/rainbow-me/rainbowkit/pull/1788

**Pull request closed without merging**
