### PR TITLE
feat: chain modal v2

### LINKED ISSUE #1299: [bug] Network switcher is hidden until a wallet is connected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.02

### wagmi Version

1.2.0

### Current Behavior

The network switcher is currently hidden when no wallet is connected.

### Expected Behavior

However, this doesn't align with the standard way of doing things. And one of the most important UX rules is to mimic the behaviors of the majority of UIs ([Jakob's law](https://lawsofux.com/jakobs-law/)).

Most multi-chains DApp allow their users to switch between networks even before a wallet is connected.
This allows users to easily browse data on each chain (e.g., yields).

Maybe showing/hiding the network switcher when a wallet is connected should be configurable through a `showSwitcher: "always" | "connected"` prop of the `<ConnectButton/>` component.

### Steps To Reproduce

_No response_

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://www.rainbowkit.com/

### Anything else?

_No response_

### LINKED ISSUE #1418: [bug] Chains not shown for Connect Button if only one chain
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.8

### wagmi Version

0.12.8

### Current Behavior

The chain button that toggles switch chains dropdown would not show if there is only one chain available.

https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/ConnectButton/ConnectButton.tsx#L71C15-L71C15

### Expected Behavior

It should be a configurable option to hide the button if there is only one chain available.

Otherwise we'd need to always rely on custom connect button to show the current chain.

### Steps To Reproduce

_No response_

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by 0xmkh**
## Changes
- Now you can choose any chains even if your wallet is not connected.
- Works with `siwe`.
- During connection process, it automatically selects the chain you picked earlier. Or the one you set as your default `initialChain` instead.
- If you've set `initialChain`, the option to change networks will be hidden to prevent accidental switches.
- The current chain will show up only even if you have one chain unless you set `chainStatus` to `none`

## Screen recordings / screenshots

https://github.com/rainbow-me/rainbowkit/assets/53529533/fab003eb-5526-45ca-976d-f8a8afc2e702

## What to test
1. Checkbox the `chainModalOnConnect` in the example app
2. Try opening the chain modal and switch through your desired chain
3. While connecting your wallet, confirm it connects to the chain you chose.
4. Set `initialChain` and check if the chain button is no longer visible.
5. Make sure everything works well with `siwe`. Test this connecting to your wallet first and then you should see chain button dissapear. This prevents users from switching chains with their connected wallet when they are not signed in yet.

### CODE REVIEW

**Comment by oxSaturn** [comment]
Hi, can we expect this feature soon? Been waiting for this a while.

**Comment by magiziz** [comment]
@0xartcro Apologies for this taking a while, we'll try to aim launching this as soon as possible. Please bear with us 🙏

**Comment by t0rbik** [comment]
Hey guys! Do you have any progress on this?

**Comment by rakpawel** [comment]
Hello! That would be super useful to have :)

**Comment by magiziz** [comment]
@rakpawel Apologies for taking a bit long on this. We're deprioritizing this at the moment, but i'll let you guys know when it's merged 👍

**Comment by magiziz** [comment]
@rakpawel @t0rbik Apologies for taking a bit long on this. We're deprioritizing this at the moment, but i'll let you guys know when it's merged 👍

**Comment by Alexangelj** [comment]
+1 to getting this in

**Comment by magiziz** [comment]
@Alexangelj We're aiming to get this in very soon.

**Comment by rakpawel** [comment]
> @Alexangelj We're aiming to get this in very soon.

awesome, waiting with update to get it in :)

**Comment by magiziz** [comment]
@rakpawel We'll have this PR on hold for now, since there might be some new EIP's introduced.

**Comment by encryptedDegen** [comment]
Any update on this? Our app would greatly benefit from that functionality.

**Comment by akshatmittal** [comment]
Hey @DanielSinclair, why was this closed? Have been looking forward to this one for a while.

**Comment by oxSaturn** [comment]
> @rakpawel We'll have this PR on hold for now, since there might be some new EIP's introduced.

Where can we track this new EIP?

**Pull request closed without merging**
