### PR TITLE
feat: submit fin wallet rainbowkit

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by magiziz** [comment]
@khiemsoft Thanks for raising the PR! I'll look into into this shortly 👍

**Comment by Vt2049** [comment]
> _ไม่มีคำอธิบายให้ไว้_

ครับ

**Comment by magiziz** [comment]
@khiemsoft Seems like Fin Wallet has some issues with the Wagmi library.

- I can't seem to get the correct `chainId` from `useAccount` hook. It gives me back `NaN`.
```tsx
const { chainId } = useAccount();
console.log(chainId); // NaN
```
- Also i'm not able to send a transaction. Instead i get this screen.

fin_wallet_tx_fail

**Comment by DanielSinclair** [comment]
@khiemsoft Noticed some lint issues. Please reopen with fixes and "Maintainers are allowed to edit this pull request"

**Pull request closed without merging**
