### PR TITLE
feat: add Enkrypt

### PR DESCRIPTION
**Pull request by andrewdahn**
Add Enkrypt to list of wallets

### CODE REVIEW

**Comment by markdalgleish** [comment]
Thanks for the PR!

We've just re-worked RainbowKit internals in v0.7 so that wallets can be imported individually, ensuring our bundle size doesn't keep increasing as we continue to add more wallets.

Thanks for giving us access to your fork — I've pushed some updates to your PR migrating it to the new API and making some minor changes. Once I've prepared a few more wallet PRs to batch together, I'll get this one merged.

**Comment by markdalgleish** [comment]
I just tried this integration and noticed the following:
- On mobile, I'm presented with the Enkrypt icon but nothing happens when I tap on it.
- The mobile download links are for MEW wallet, not Enkrypt, even though you also have a [separate PR adding MEW wallet.](https://github.com/rainbow-me/rainbowkit/pull/777) It seems like Enkrypt is only available as a browser extension, is that right? If so, should this wallet option be hidden on mobile?

**Comment by andrewdahn** [comment]
> I just tried this integration and noticed the following:
> 
> * On mobile, I'm presented with the Enkrypt icon but nothing happens when I tap on it.
> * The mobile download links are for MEW wallet, not Enkrypt, even though you also have a [separate PR adding MEW wallet.](https://github.com/rainbow-me/rainbowkit/pull/777) It seems like Enkrypt is only available as a browser extension, is that right? If so, should this wallet option be hidden on mobile?

Hello,

I removed the MEW wallet links to iOS and Playstore, and I added a link to our Enkrypt site on the mobile view.

**Comment by andrewdahn** [comment]
> I just tried this integration and noticed the following:
> 
> * On mobile, I'm presented with the Enkrypt icon but nothing happens when I tap on it.
> * The mobile download links are for MEW wallet, not Enkrypt, even though you also have a [separate PR adding MEW wallet.](https://github.com/rainbow-me/rainbowkit/pull/777) It seems like Enkrypt is only available as a browser extension, is that right? If so, should this wallet option be hidden on mobile?

Hello,
I removed the MEW wallet links to iOS and Playstore, and I added URI for mobile.

**Comment by andrewdahn** [comment]
> > I just tried this integration and noticed the following:
> > 
> > * On mobile, I'm presented with the Enkrypt icon but nothing happens when I tap on it.
> > * The mobile download links are for MEW wallet, not Enkrypt, even though you also have a [separate PR adding MEW wallet.](https://github.com/rainbow-me/rainbowkit/pull/777) It seems like Enkrypt is only available as a browser extension, is that right? If so, should this wallet option be hidden on mobile?
> 
> Hello, I removed the MEW wallet links to iOS and Playstore and added URI for mobile.

@markdalgleish Hello, pinging you to see if I can get another review on this along with the MEW wallet pull request. Thank you.

**Pull request closed without merging**
