### PR TITLE
feat: foxWallet support

### PR DESCRIPTION
**Pull request by icodeface**

### CODE REVIEW

**Comment by icodeface** [comment]
@DanielSinclair the issue should be fixed, could u check again

**Comment by icodeface** [comment]
@DanielSinclair kindly pls check again

**Comment by icodeface** [comment]
@DanielSinclair seems all the issue have been fixed ? Could u update the labels, thanks

**Comment by icodeface** [comment]
> @icodeface Please enable changes from maintainers on this PR

Sorry, i cannot find the option "Allow edits from maintainers" in this page, could be the issue: https://github.com/orgs/community/discussions/5634

So i just add you to [my repo](https://github.com/foxwallet/rainbowkit) with write permission, is it ok ?

image

**Review by nickbytes — APPROVED** [review]

**Pull request merged**
