### PR TITLE
feat: zealWallet support

### PR DESCRIPTION
**Pull request by masm**
There are a few `@ts-expect-error` due to `window.ethereum.isZeal` not being declared yet in the wagmi version used. This has been fixed in wagmi - merged PR here: https://github.com/wagmi-dev/wagmi/pull/2973/files. We will be able to remove these in short order.

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@masm Going forward, RainbowKit will adopt [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) for injected wallets and won't pull in new wallets to RainbowKit. It is recommended that you begin supporting this standard in your wallet via [mipd](https://github.com/wagmi-dev/mipd). This will automatically be supported for dApps in an upcoming release of RainbowKit alongside Wagmi v2. You can test your wallet against a test dApp at [eip6963.org](https://eip6963.org/) in the meantime.

**Comment by masm** [comment]
With the upgrade of wagmi, @ts-expect-error no longer required. Anything else preventing merge?

**Comment by DanielSinclair** [comment]
@masm Looking to get this merged. Can you share early access for me to QA? Signed up to the Typeform

**Comment by DanielSinclair** [comment]
@masm When testing, I am seeing an issue with the injection behavior. It is not detected at load-time, possibly because `window.ethereum.isZeal` is injected too slowly, or the provider is failing Wagmi's `ready` logic here: https://github.com/wagmi-dev/wagmi/blob/38306606d2fd72a4c6918323bf86a1afda348638/packages/connectors/src/injected.ts#L88

**Comment by DanielSinclair** [comment]
I'll proceed to merge, but note that this is currently not functional for end users on the wallet side

**Review by DanielSinclair — APPROVED** [review]

**Pull request merged**
