### PR TITLE
feat: add bloom wallet

### PR DESCRIPTION
**Pull request by MarkNerdi**
This PR adds `Bloom Wallet` to the list of connectors in RainbowKit

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@MarkNerdi Thanks for the contribution! Can you add a changeset and the new wallet to the `packages/example` dApp and the `en-US` Custom Wallet List doc? Here is another example: https://github.com/rainbow-me/rainbowkit/pull/1596/files

**Comment by MarkNerdi** [comment]
@DanielSinclair Updated the PR :+1:

**Comment by MarkNerdi** [comment]
@DanielSinclair

**Comment by DanielSinclair** [comment]
@MarkNerdi Seeing linting issues and a CI failure

**Comment by MarkNerdi** [comment]
@DanielSinclair Sorry for that :sweat:  Linting is fixed now

**Comment by MarkNerdi** [comment]
@DanielSinclair
The checks all have passed. Just pinging again, so it won't be a stale PR :relaxed:

**Comment by nicole-obrien** [comment]
@DanielSinclair do you have time to review this please 🙏

**Comment by nicole-obrien** [comment]
@KosmosKey @DanielSinclair This PR has bee open a while now, please could we request that the PR is reviewed so that dApps in the Shimmer and IOTA ecosystem can easily add support for Bloom wallet on their dApps. Many thanks, Nicole [bloomwallet.io](bloomwallet.io)

**Comment by KosmosKey** [comment]
@nicole-obrien We just launched v2 and we've introduced a new way of adding wallets. Are you able to update your code ? Here is an example for [WalletConnect](https://www.rainbowkit.com/docs/custom-wallets)

Here is an example of an injected wallet setup ([brave wallet](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/wallets/walletConnectors/braveWallet/braveWallet.ts))

**Comment by MarkNerdi** [comment]
@KosmosKey 
Updated the code and examples :+1:

**Comment by KosmosKey** [comment]
@MarkNerdi Thanks. We'll come back to this PR soon please bear with us 🙏

**Comment by KosmosKey** [comment]
@MarkNerdi Closing this PR since we've opened a new one here: https://github.com/rainbow-me/rainbowkit/pull/1784

Easier for us to push code and new translations. 

Quick question tho it seems that bloom wallet has a small bug [here](https://github.com/rainbow-me/rainbowkit/pull/1784). Do you mind responding to the comment i've made and see why that might be happening ?

**Pull request closed without merging**
