### PR TITLE
Update Trust Wallet connector and other changes

### PR DESCRIPTION
**Pull request by george-gkas**
Please look at the [relevant discussion page](https://github.com/rainbow-me/rainbowkit/discussions/949) for all the introduced changes.

Tasks:
- [x] QA (completed)

### CODE REVIEW

**Review by DanielSinclair — CHANGES_REQUESTED** [review]
Hi George! Thanks for your contribution here. A few top-level things we'd like to change before working to review changes to the Trust Wallet connector:
- Revert craco, webpack, and package.json changes
- Revert example changes
- Revert addition of Trust Wallet to `getDefaultWallets`; we are working on a more sustainable solution for the wallet popularity problem, and would like to keep RainbowKit focused on connector functionality

**Comment by DanielSinclair** [comment]
Thanks for bringing all of these to our attention @george-gkas. Here's the current plan:
- Currently reviewing #922. Will get that Remix issue fix merged
- Just opened #951 to resolve the CRA polyfill issue; this approach is closer to our recommendations for Vite and Remix
- We'll punt on the source map warnings for now; want this example to be as close as possible to what `create-react-app` would spit out. Hopefully they resolve those issues soon.
- Please open a 2nd PR with `publicProvider` changes; we'll try to get that merged in upstream before this
- Hoping to just review the Trust Wallet connector here once the revert is ready; apologies for the run-around, but we want to work with minimally scoped PRs

**Comment by DanielSinclair** [comment]
Hi @george-gkas. Am seeing a few significant reliability issues with this connector on our example dApp: https://rainbowkit-example-git-fork-george-gkas-tru-94a50d-rainbowdotme.vercel.app/
1) The "Connect to Trust Wallet" prompt appears on page-load and refresh after the first accepted connection
2) The detector is not reliable; am regularly seeing the WalletConnect fallback while `window.ethereum.isTrust` is injected
3) The dApp connect state display in Trust does not appear to be in sync with the actual provider state; am always seeing a green status after rejection
4) The connector is not playing well alongside MetaMask when both wallets are active. We do see injection race conditions that break detection, but this is unexpected: https://user-images.githubusercontent.com/4412473/213771306-a39c1f4c-0a35-4619-bc59-a53e55e00dd2.mp4

**Comment by DanielSinclair** [comment]
@george-gkas Great, I'll do that! `daniel @ rainbow.me`

**Review by DanielSinclair — APPROVED** [review]

**Comment by DanielSinclair** [comment]
@george-gkas Thanks for working on these improvements and detailed documentation. Will do a few more QA tests to make sure both the MetaMask and Trust connector changes are stable. Do you mind enabling `Allow edits from maintainers` on the PR, or bumping the fork with an empty commit? That'll deploy a new `rainbowkit-example` test deployment

**Comment by DanielSinclair** [comment]
@george-gkas This issue sometimes will only appear in the deployed example because RainbowKit is bundled and optimized and will therefore load faster than a slow injector can inject. You would see the same behavior on real-world dApps. This does appear to be a Trust Wallet specific issue because it doesn’t occur for MetaMask.

**Comment by DanielSinclair** [comment]
I've found an additional issue where only the Trust connector works or vice versa when MetaMask is active. Was fixing this the intended goal of modifying the MetaMask connector? If possible, we'd like this behavior to work as well. RainbowKit's goal is to allow multiple wallets to work simultaneously.
https://user-images.githubusercontent.com/4412473/217293393-232dd2d9-69dd-4752-b97f-0ebae3f0ac17.mov

**Comment by DanielSinclair** [comment]
@george-gkas It looks like `0.0.229` is still the current prod version. I'm still seeing the same reliability issues, including:
- Unreliable detection
- Conflicting MetaMask and Trust behavior

We can get this merged as soon as these issues are addressed. We would like Trust to retain one of the "default wallet" positions, but the extension behavior is a regression that we wouldn't want to release to every dApp.

https://user-images.githubusercontent.com/4412473/218518359-e5a497df-2306-4e9b-8ef4-aa2a7644e0aa.mov

**Comment by DanielSinclair** [comment]
@george-gkas A few extensions built on Manifest v3 aren’t experiencing this issue. Once Trust is working reliably in production, we can look at this again. If there are improvements to RainbowKit that would improve this on our end, we’d be happy to review those PRs and discussions as well.

**Comment by DanielSinclair** [comment]
@george-gkas Zerion's team made progress after encountering similar behavior. Rainbow fortunately didn't bump into this as well. A bit of a dark forest but there are viable paths. Am open to improvements to RainbowKit's logic with a polling system (or ideally something better) as well in a new PR or Issue to discuss what can be done.

**Comment by DanielSinclair** [comment]
@george-gkas The injector is definitely more reliable. Awesome to see your team get over that hurdle.
Still seeing a few issues:
1. MetaMask selection UI is not working; I think this is related to `isMetaMask` being false on the trust provider. Wagmi/RainbowKit don't account for `isMetaMask` being false while `isTrust` is true. Is this something we have to consider for an unknown reason, or can we revert that? Most of the supply chain is looking for both of these flags to be true for detection, else wonky behavior appears.
2. `window.ethereum.providers` is empty, so the MetaMask provider isn't available for simultaneous wallet operations/detection
https://user-images.githubusercontent.com/4412473/222793721-90d3b6cb-8a0e-4a14-90c3-1fc920f6523e.mov

**Comment by GeorgeGkas** [comment]
Regarding the first point `trustwallet` provider is implemented to have `isMetaMask=false` and `isTrust=true`. 

Regarding the second point PR #1128  will solve the issue based on the check introduced in https://github.com/rainbow-me/rainbowkit/pull/1128/files#diff-9754437de1e97d46408f65b4a5a48eaf2aa94984b153a9bed44daadb37ae183aR67. We have to wait for that to be merged to update our PR and test again.

**Comment by GeorgeGkas** [comment]
We include it because it caused issues with many dApps and is [not part of the standard](https://eips.ethereum.org/EIPS/eip-1193), but I see that connection works with the latest preview demo. Download the latest release of [Trust Wallet ](https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph) and MetaMask. Enable both wallets. Open the app and deselect "Set As A Default Wallet". Then load the demo and verify that you can connect MetaMask and TrustWallet.

Screenshot 2023-04-06 at 5 52 55 PM

**Comment by DanielSinclair** [comment]
@GeorgeGkas Having a hard time understanding. Is `window.ethereum.providers` supported and I'm just encountering a bug, or is it unsupported? It's not part of EIP-1193, but support is fairly widespread and mostly aligns with the proposed `window.evmProviders` EIP-5749 standard. The idea being that if the default wallet is overriden, the user can still use MetaMask as long as the dApp looks for `window.ethereum.providers`. This is what RainbowKit will favor so that the MetaMask button always respects MetaMask.

**Comment by DanielSinclair** [comment]
Closing in favor of #1174 for merge

**Pull request closed without merging**
