### PR TITLE
fix: grab all mobile + separate ipad

### PR DESCRIPTION
**Pull request by nicoglennon**
fix mobile issues with using other browsers other than safari

image

^chrome

### CODE REVIEW

**Comment by sashadev-sky** [comment]
this didn't fix it for me unfortunately - iPhone 12 PRO v. 15.3 using any browser besides safari (all latest updates). If it is a user agent string problem though (will check that out) then maybe it should be expanded to cover more cases

**Comment by sashadev-sky** [comment]
more info: the user agent strings seems to match, but for whatever reason it loads the desktop version

**Comment by sashadev-sky** [comment]
Sorry i wasn't pulling in the updated package - hard to tell with yarn sometimes! thank you for this fix 🙏

**Comment by sashadev-sky** [comment]
@RainbowWalletAdmin can someone please approve this its a pretty critical bug

**Comment by peduarte** [comment]
Hey! we'll look into this asap. Thanks fren

**Review by peduarte — APPROVED** [review]
lfg

**Pull request merged**
