### PR TITLE
fix: chains overflow on mobile

### LINKED ISSUE #1007: [bug] fixed too many items in chains breaking UI on mobile (overflow)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

latest

### wagmi Version

latest

### Current Behavior

Hey rainbow kit team,

when you have too many chains on mobile, they don't all show up, and block the "close" button from view. here is the fix. (see pictures)

The fix simply adds overflow scroll and a max width of 90vh, it should not interact with any logic whatsoever.

Current behavior
image

### Expected Behavior

Fixed behaviour 
image
Thanks

### Steps To Reproduce

same chains for reproduction ([...chains, ...chains, ...chains, ...chains] in ChainModal.tsx

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

Fixed contribution pull request:

https://github.com/rainbow-me/rainbowkit/pull/998

### PR DESCRIPTION
**Pull request by brieyla1**
Hey rainbow kit team,

when you have too many chains on mobile, they don't all show up, and block the "close" button from view. here is the fix. (see pictures)

The fix simply adds overflow scroll and a max width of 90vh, it should not interact with any logic whatsoever.

Current behavior
CleanShot 2023-02-02 at 20 10 51@2x

Fixed behaviour (same chains for reproduction (`[...chains, ...chains, ...chains, ...chains]` in `ChainModal.tsx`)
CleanShot 2023-02-02 at 20 12 15@2x

Thanks

### CODE REVIEW

**Comment by brieyla1** [comment]
take a look @DanielSinclair :)

My client wants this updated asap...

Thank you, sorry for the rush.

**Comment by brieyla1** [comment]
up

**Comment by DanielSinclair** [comment]
Hey @brieyla1. A few refactors we'd like to see before getting this merged:
- Let's use the `.css.ts` convention instead of inline styles. Checkout an example like `ConnectOptions/MobileOptions.css.ts`
- Run `pnpm run lint --fix` to make eslint happy

**Comment by DanielSinclair** [comment]
Mobile Test: 
IMG_7702

Desktop Tests:
Screenshot 2023-09-28 at 2 29 15 AM
Screenshot 2023-09-28 at 2 31 24 AM

**Comment by KosmosKey** [comment]
Good to go 👍

Screenshot 2023-09-27 at 21 24 09

Screenshot 2023-09-28 at 16 54 05


@brieyla1 Just make sure to go for `.css.ts` convention and can be merged.

**Review by 0xmkh — APPROVED** [review]

**Comment by CJskii** [comment]
@DanielSinclair I run ``"@rainbow-me/rainbowkit": "^1.0.11"``, but my modal still doesn't have scroll. 

I was just wondering if there's anything additional that I should enable or do to get scroll working.

**Comment by DanielSinclair** [comment]
@CJskii This will be released later today as 1.0.12

**Pull request merged**
