### PR TITLE
fix: compatible wagmi config type for `getDefaultConfig`

### PR DESCRIPTION
**Pull request by ponjs**
Compatible with wagmi [config type](https://wagmi.sh/react/typescript#config-types)

```ts
const config = getDefaultConfig({
  appName: 'RainbowKit demo',
  projectId: 'YOUR_PROJECT_ID',
})

declare module 'wagmi' { 
  interface Register { 
    config: typeof config 
  } 
} 
```

### CODE REVIEW

**Comment by ponjs** [comment]
> @ponjs Hello! What issue are you aiming to fix here? Can you add an explainer?

Because the current config type prompts `'config' is referenced directly or indirectly in its own type annotation`.

**Comment by DanielSinclair** [comment]
@ponjs What versions of Wagmi and Viem are you currently using?

**Comment by ponjs** [comment]
> @ponjs What versions of Wagmi and Viem are you currently using?

```
"@rainbow-me/rainbowkit": "^2.0.2",
"viem": "^2.9.3",
"wagmi": "^2.5.13",
```

**Comment by magiziz** [comment]
@ponjs Just realised that `WagmiProviderProps['config']` is no longer being used as the type in their `<WagmiProvider />` component with `config` prop. Did some cleanup for you to not return `WagmiProviderProps['config']` as a return prop for `getDefaultConfig`.

**Comment by ponjs** [comment]
> @ponjs Just noticed that `WagmiProviderProps['config']` is kind of funky with `createConfig` type itself. Did some cleanup for you to not return `WagmiProviderProps['config']` as a return prop for `getDefaultConfig`.

Hello, but this is missing the generic type, which prevents it from inferring the value of chainId, since declaring the type of config serves the purpose of needing to get the value of chainId. The [documentation](https://wagmi.sh/react/typescript#declaration-merging) also mentions.

image

**Comment by magiziz** [comment]
@ponjs Just made type even more stricter. Should work now. Let me know if it looks good 👍

image

**Comment by ponjs** [comment]
> @ponjs Just made type even more stricter. Should work now. Let me know if it looks good 👍
> 
> image

👍 Thanks, that's what I was trying to achieve

**Review by DanielSinclair — APPROVED** [review]

**Pull request merged**
