### PR TITLE
initial lukso wallet

### PR DESCRIPTION
**Pull request by Heisenburgirs**
This is initial commit for adding Lukso's injected wallet "Universal Profile".

I'm not sure if I've everything correct, let me know which existing wallet fits the category so I can follow it accordingly.

It is an injected wallet that lives in window.lukso

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@Heisenburgirs Am seeing CI issues. Please also replicate connectors exactly, including adding strings from our en_US locale.

**Comment by Heisenburgirs** [comment]
I think that should do it.

**Comment by Heisenburgirs** [comment]
Oeps, my bad.

**Comment by DanielSinclair** [comment]
@Heisenburgirs You should aim to get the Lukso chain added to the `viem/chains` package (proxied by `wagmi/chains`) here: https://github.com/wevm/viem/tree/main/src/chains

**Comment by DanielSinclair** [comment]
Will close for now because the CI tests are still failing and our connector format has changed with RainbowKit v2. If the wallet supports EIP-6963, RainbowKit v2 will detect and support the wallet automatically. Reference the test dApp and docs here: https://eip6963.org/

**Pull request closed without merging**
