### PR TITLE
feat: expose useRecentTransactions hook

### PR DESCRIPTION
**Pull request by spennyp**

### CODE REVIEW

**Comment by spennyp** [comment]
Adds feature discussed here: https://github.com/rainbow-me/rainbowkit/discussions/373

**Comment by shrugs** [comment]
++ access to the rainbowkit transaction store would be a nice upgrade for my project — the tx store does exactly what i want, (although would also like to be able to annotate txs with additional info so i can filter them app-side) so i've resorted to copying the TransactionStore itself into my project and writing my own hooks, then dual-publishing to rainbow's internal store.

**Comment by smakosh** [comment]
> ++ access to the rainbowkit transaction store would be a nice upgrade for my project — the tx store does exactly what i want, (although would also like to be able to annotate txs with additional info so i can filter them app-side) so i've resorted to copying the TransactionStore itself into my project and writing my own hooks, then dual-publishing to rainbow's internal store.

About to do the same thing. Feels bad having the same code around when the solution needs just to be exported.

**Review by smakosh — APPROVED** [review]

**Comment by aj-may** [comment]
Can/should we add docs for this? 📚

**Comment by DanielSinclair** [comment]
Thanks for the contribution @spennyp

**Pull request closed without merging**
