### PR TITLE
feat: wigwam wallet support

### PR DESCRIPTION
**Pull request by serg-plusplus**
Wigwam Web3 extension - https://wigwam.app

### CODE REVIEW

**Comment by DanielSinclair** [comment]
@serg-plusplus Can you enable "Allow edits from maintainers"? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by serg-plusplus** [comment]
> @serg-plusplus Can you enable "Allow edits from maintainers"? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

I cant see this button. I suppose because we made a fork under our github orginisation: https://github.com/orgs/community/discussions/5634
I can resubmit the PR from my personal account if necessary. Or make some changes on my own.

**Comment by DanielSinclair** [comment]
@serg-plusplus Okay. I think the only change we need is to revert the locale changes and just keep`en-US`; that is managed by our translation system.

**Comment by serg-plusplus** [comment]
> @serg-plusplus Okay. I think the only change we need is to revert the locale changes and just keep`en-US`; that is managed by our translation system.

Completed. I've reverted the other locales. Only left en_us.

**Review by DanielSinclair — APPROVED** [review]

**Pull request merged**
