### PR TITLE
feat: safepalWallet support

### PR DESCRIPTION
**Pull request by QiAbc**
Please let me know if you have any questions, thank you

### CODE REVIEW

**Comment by DanielSinclair** [comment]
Seeing a minor deployment error. Running `pnpm run lint:fix` should resolve the issue
> 41:3  Error: Member 'safepalWallet' of the import declaration should be sorted alphabetically.  sort-imports

**Comment by QiAbc** [comment]
> Seeing a minor deployment error. Running `pnpm run lint:fix` should resolve the issue
> 
> > 41:3  Error: Member 'safepalWallet' of the import declaration should be sorted alphabetically.  sort-imports

It has been resubmitted, please take a look at it

**Comment by QiAbc** [comment]
> Seeing a minor deployment error. Running `pnpm run lint:fix` should resolve the issue
> 
> > 41:3  Error: Member 'safepalWallet' of the import declaration should be sorted alphabetically.  sort-imports

When will the code be merged?

**Comment by DanielSinclair** [comment]
@QiAbc When QAing, I am seeing quite a few issues:
1) For unsupported networks when attempting to switch via WalletConnect, it appears an error isn't properly returned from the mobile wallet
Screenshot 2023-10-15 at 5 11 08 PM
2) I was unable to successfully test the injection flow; it appears the inpage script is throwing an error. Otherwise, this is possibly one of the following: `window.ethereum` is not detected at load-time, possibly because window.ethereum.isZeal is injected too slowly 2) the provider is failing Wagmi's ready logic here: https://github.com/wagmi-dev/wagmi/blob/38306606d2fd72a4c6918323bf86a1afda348638/packages/connectors/src/injected.ts#L88
Screenshot 2023-10-15 at 5 11 12 PM

**Comment by DanielSinclair** [comment]
I'll proceed to merge, but note that the extension path is not functional for end users on the wallet side

**Review by DanielSinclair — APPROVED** [review]

**Pull request merged**
